server.port=5000
server.address=0.0.0.0

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/PlayX_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Saran@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
music.storage.path=${MUSIC_STORAGE_PATH:uploads/music}
music.covers.path=${MUSIC_COVERS_PATH:uploads/covers}

# JWT Settings
jwt.secret=2B7JFnTIOgpsLXgJj5UKM5oWUcLG500a6LB7Fk/Wtme5X01U897jLl2xMBZZAwQqlaeq6Poc+HA1YGd9RSTAYA==
jwt.expiration=604800000
